FROM node:18-alpine

# Create app directory
WORKDIR /app

RUN apk --no-cache update

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package.json ./
COPY prisma ./prisma/

# Install app dependencies
RUN npm install

COPY . .


# EXPOSE 3000

RUN npm rebuild bcrypt --build-from-source

# Start the server using the production build
CMD ["sh", "-c", "tail -f /dev/null"]
# CMD [ "npm", "run", "start:migrate:dev" ]
# CMD ["/bin/bash", "-c", "npm run start:migrate:dev"]
